-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 19:03:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_project_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_project_type` (
  `project_type_id` INT NOT NULL AUTO_INCREMENT,
  `project_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`project_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_title` VARCHAR(45) NOT NULL,
  `project_deadline` DATE NOT NULL,
  `project_cost` VARCHAR(45) NOT NULL,
  `project_status` VARCHAR(45) NOT NULL,
  `project_decision_status` VARCHAR(45) NOT NULL,
  `project_received_datetime` INT NOT NULL,
  `project_type_id` INT NOT NULL,
  `project_technology` VARCHAR(45) NOT NULL,
  `project_soure` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `attached_project_document` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_tbl_Project_tbl_project_type1_idx` (`project_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_Project_tbl_project_type1`
    FOREIGN KEY (`project_type_id`)
    REFERENCES `mydb`.`tbl_project_type` (`project_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_first_name` VARCHAR(45) NOT NULL,
  `user_last_name` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_phone` INT NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_login_time` DATETIME NOT NULL,
  `user_logout_time` DATETIME NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_tbl_user_tbl_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_user_tbl_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`tbl_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user_project_assign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user_project_assign` (
  `user_project_assign_id` INT NOT NULL,
  `assign_datetime` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `assign_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_project_assign_id`),
  INDEX `fk_tbl_user_project_assign_tbl_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_tbl_user_project_assign_tbl_Project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_user_project_assign_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_project_assign_tbl_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`tbl_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_experties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_experties` (
  `user_experties_id` INT NOT NULL AUTO_INCREMENT,
  `experties_name` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_experties_id`),
  INDEX `fk_user_experties_tbl_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_experties_tbl_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`tbl_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_revision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_revision` (
  `project_revision_id` INT NOT NULL AUTO_INCREMENT,
  `revision_round` VARCHAR(45) NULL,
  `project_id` INT NOT NULL,
  `attached_r_project_document` VARCHAR(255) NULL,
  PRIMARY KEY (`project_revision_id`),
  INDEX `fk_project_revision_tbl_Project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_revision_tbl_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`tbl_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
